### ISSUE TITLE
Publish as a snap

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/asset-uploader#10]
Let's make tool snap installlable

**Comment by anthonydillon** [comment]
Happy to pair of you are. Keen to learn.

**Comment by nottrobin** [comment]
@anthonydillon happy to. Unforts it'll have to be after my holiday. I'm back on the 20th.

**Comment by nottrobin** [comment]
Done! Fixed by @anthonydillon in #13 and #14

**Comment by nottrobin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make upload-assets into a snap](https://trello.com/c/4RSUJf2c/3076-make-upload-assets-into-a-snap)
