### ISSUE TITLE
401 Unauthorised

### ISSUE THREAD

**Issue by petermakowski** [ubuntudesign/asset-uploader#42]
Uploading assets to the asset server using the snap fails with `401 Client Error: UNAUTHORIZED for url: https://assets.ubuntu.com/v1`

![image](https://user-images.githubusercontent.com/7452681/207296109-b4765d90-a9e6-44b3-99a8-0fbf1dc6e455.png)

We had to use a custom python script instead of a snap for now to workaround this: 
- https://github.com/canonical/maas-ui/blob/main/scripts/upload-assets.py
- https://github.com/canonical/maas-ui/blob/main/.github/workflows/upload.yml#L49-L55

**Comment by nottrobin** [comment]
Fixed! https://assets.ubuntu.com/v1/b09900c1-ubuntu-server-guide-2023-01-23.pdf
