### ISSUE TITLE
Simplify server options

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/asset-uploader#5]
Instead of needing `--server-url https://example.com/v1`, I think it should be more opinionated about both the `https` part and the `/v1` part - it knows it needs `https` to be properly secure, and it knows it's expecting to interact with version 1 of the API.

So:

``` bash
$ assets --server-url assets.example.com
# or
$ assets -s example.com/assets
```

Although we do need to allow for the fact that much of the time people will be using this to manage a server they're running locally. So we should at least detect whether we're pointing to `localhost` or `127.*.*.*` and use `http` in that case. And we may also want to add an `--insecure` option, for if they know what they're doing.

**Comment by WillMoggridge** [comment]
This was marked resolved with referenced PR. Closing.
