### ISSUE TITLE
Make command usable as a module

### ISSUE THREAD

**Issue by WillMoggridge** [ubuntudesign/asset-uploader#6]
Seperate command line arguments and core methods, allowing us to use this module directly from another python script if we wish to.

Example: https://en.wikibooks.org/wiki/Python_Programming/Modules#Making_a_program_usable_as_a_module

**Comment by nottrobin** [comment]
@WillMoggridge - is this solved by #12 ?

**Comment by WillMoggridge** [comment]
It sounds like it is
